version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:+Vazz+kHYJ88sjHwKKn7rWvj9QqVsxlE4MEX6HCYC/s=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=ixocakuy_tambowork
      - DB_USERNAME=ixocakuy_tambowork
      - DB_PASSWORD=Tambowork123
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ixocakuy_tambowork
      MYSQL_USER: ixocakuy_tambowork
      MYSQL_PASSWORD: Tambowork123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d  # Este es el volumen que carga el archivo base_datos.sql
       
volumes:
  mysql_data:
    driver: local
